import React, { useState, useEffect } from 'react';
import { attainmentAPI } from '../api';
import { Lightbulb, CheckCircle2, ArrowRight, RefreshCw, Layers } from 'lucide-react';

export default function Recommendations({ courseState, refreshState, activeSubjectId }) {
  const [recommendations, setRecommendations] = useState([]);
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    if (courseState && courseState.subject_name === activeSubjectId) {
      setRecommendations(courseState.recommendations || []);
    }
  }, [courseState, activeSubjectId]);

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const response = await attainmentAPI.generateRecommendations();
      setRecommendations(response.data);
      refreshState();
    } catch (err) {
      alert('Failed to generate improvement recommendations. Make sure you calculated attainment first.');
    } finally {
      setLoading(false);
    }
  };

  const getPriorityClass = (priority) => {
    if (priority.toLowerCase() === 'high') return 'badge-red';
    if (priority.toLowerCase() === 'medium') return 'badge-orange';
    return 'badge-blue';
  };

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-2xl font-bold font-sans tracking-tight">AI-Generated Curriculum Recommendations</h2>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Actionable improvement suggestions generated by analyzing weak CO/PO attainment benchmarks.
          </p>
        </div>

        {recommendations.length > 0 && (
          <button
            onClick={handleGenerate}
            disabled={loading}
            className="flex items-center gap-1.5 px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-sm font-semibold rounded-xl shadow-md transition-colors"
          >
            <RefreshCw className="w-4 h-4" />
            Refresh Analysis
          </button>
        )}
      </div>

      {recommendations.length === 0 ? (
        <div className="glass-panel p-8 text-center max-w-xl mx-auto space-y-4">
          <div className="w-16 h-16 rounded-full bg-blue-50 dark:bg-blue-950/40 flex items-center justify-center text-blue-600 mx-auto">
            <Lightbulb className="w-8 h-8" />
          </div>
          <div>
            <h3 className="text-lg font-bold">Generate Improvement Recommendations</h3>
            <p className="text-sm text-slate-400 mt-1">
              Analyze CO/PO attainment levels and suggest modifications to class assignments, tutorials, or syllabus layouts.
            </p>
          </div>
          <button
            onClick={handleGenerate}
            disabled={loading || !courseState?.co_attainment?.length}
            className="w-full py-3 bg-blue-600 hover:bg-blue-500 text-white font-semibold rounded-xl shadow-md transition-colors disabled:opacity-50"
          >
            {loading ? 'Analyzing data and generating...' : !courseState?.co_attainment?.length ? 'Prerequisite: Calculate Attainments first' : 'Generate Recommendations'}
          </button>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {recommendations.map((rec, i) => (
            <div key={i} className="glass-card p-5 flex flex-col justify-between gap-4 border-t-4 border-t-amber-500 dark:border-t-amber-600/50">
              <div className="space-y-3">
                <div className="flex items-center justify-between">
                  <span className="text-xs font-bold text-slate-400 uppercase">Target: {rec.target}</span>
                  <span className={getPriorityClass(rec.priority)}>
                    {rec.priority} Priority
                  </span>
                </div>
                
                <div className="space-y-1">
                  <span className="block text-[10px] font-bold text-slate-400 uppercase tracking-wide">Issue Identified</span>
                  <p className="text-sm font-semibold text-slate-800 dark:text-slate-200">{rec.issue}</p>
                </div>
              </div>

              <div className="bg-slate-50 dark:bg-slate-950/60 p-3 rounded-xl border border-slate-100 dark:border-slate-850/60 mt-2">
                <span className="block text-[9px] font-bold text-slate-400 uppercase tracking-wide mb-1 flex items-center gap-1">
                  Action Suggestion
                </span>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed font-medium">
                  {rec.suggestion}
                </p>
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
